name: Pylint Check

on: [push]

jobs:
  static-analysis:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.8", "3.9", "3.10"]

      permissions:
        contents: read
        security-events: write
        checks: write
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install project dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pylint schedule  # Install both linter and required package

      - name: Run Pylint analysis
        run: |
          pylint --disable=unused-argument $(git ls-files '*.py')
